version: "3.8"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: source_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: processed_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # S3-compatible endpoint
      - "9001:9001"  # MinIO Console
    volumes:
      - minio_data:/data

  airflow-webserver:
    build: ./airflow
    container_name: airflow-webserver
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - kafka
      - mysql
      - minio
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./great_expectations:/opt/airflow/great_expectations

  spark:
    build: ./spark
    container_name: spark
    depends_on:
      - kafka
      - mysql
      - minio
      - postgres
    volumes:
      - ./spark:/opt/spark_jobs
      - ./great_expectations:/opt/spark_jobs/great_expectations

volumes:
  minio_data:
